# Generated by Django 5.1.3 on 2024-12-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animalmeasurement_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmeasurement',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='animalmeasurement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
